AllCops:
  TargetRubyVersion: 2.6

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Naming/UncommunicativeMethodParamName:
  MinNameLength: 1

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/*.rb'
    - 'interop/*.rb'

Metrics/LineLength:
  Exclude:
    - 'tttls1.3.gemspec'
