on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - uses: thekuwayama/openssl@master
        with:
          ruby-version: '2.6.x'
      - run: gem install bundler
      - run: bundle install
      - run: docker pull thekuwayama/openssl
      - run: bundle exec rake
      - run: bundle exec rake interop
